### ISSUE TITLE
[Feat] 카카오 소셜 로그인 및 JWT 인증 시스템 구현

### ISSUE THREAD

**Issue by supsup-hae** [IT-Cotato/10th-ODIT-BE#11]
### 💼 작업 설명

Spring Security와 JWT를 이용한 카카오 소셜 로그인 시스템을 구현

### ✅ To-do

- [x] 프로젝트 의존성 및 카카오 개발자 설정
- [x] OAuth2 설정 (`application.yml`)
- [x] User 엔티티 구현
- [x] SecurityConfig 구성
- [ ] JWT 인증 필터 구현
- [x] OAuth2 인증 핸들러 구현
