### ISSUE TITLE
[Fix] CI/CD 배포를 위한 서버 환경설정 코드 수정

### ISSUE THREAD

**Issue by supsup-hae** [IT-Cotato/10th-ODIT-BE#21]
### 💼 작업 설명

- 서버 배포 환경을 고려하지 않은 코드로 인해 EC2 배포 시 환경설정 값이 정상적으로 적용되지 않는 문제가 발생
### ✅ To-do

- [x] application.yml 환경설정 분리
- [x] 서버 환경 변수 설정 방식 수정
- [x] 환경별 프로필 설정 추가
- [x] 에러 이슈 템플릿 추가
