### ISSUE TITLE
[Feat] Global Exception 구현

### ISSUE THREAD

**Issue by supsup-hae** [IT-Cotato/10th-ODIT-BE#5]
### 💼 작업 설명

Global Exception 구현

### ✅ To-do

- [x] 에러 코드 정의
- [x] 에러 응답 코드 정의
- [x] 전역 예외 핸들러 구현
